theme: pages-themes/leap-day@v0.2.0
title: Samuel Costas Portfolio
description: I am a Mechanical and Project engineer. My passion is building different software and electronics projects. Check out my side-projects below.
